export const editorCopy = {
  title: (when: string) => `Post du ${when}`,
  previous: "Post précédent (K)",
  next: "Post suivant (J)",
  close: "Fermer (Échap)",
  loading: "Chargement du post…",
  notFound: "Ce post n'existe plus ou a été supprimé.",
  fields: {
    publisher: "Publié par",
    date: "Jour",
    time: "Heure",
    format: "Format",
    content: "Contenu lié",
    contentNone: "Aucun",
    angle: "Sujet / angle",
    angleHint: "Note interne : l'idée à développer dans ce post.",
    anglePlaceholder: "Ex. : le témoignage du DSI sur la conduite du changement.",
    body: "Texte du post",
    bodyPlaceholder: "Rédigez le texte tel qu'il sera publié…",
    youtubeTitle: "Titre YouTube",
    youtubeDescription: "Description YouTube",
    youtubeTags: "Tags YouTube",
    youtubeTagsHint: "Séparés par des virgules.",
    linkTo: "Lien vers",
    linkToHint: "La vidéo vers laquelle ce post renvoie (par exemple la vidéo longue).",
    linkToNone: "Aucun lien",
    linkToUrl: "Ou une adresse web",
    relatedVideo: "Vidéo associée ajoutée dans YouTube Studio",
    relatedVideoHint: "À cocher une fois le lien vers la vidéo longue réglé dans Studio.",
  },
  counter: (count: number, max: number) =>
    `${count.toLocaleString("fr-FR")} / ${max.toLocaleString("fr-FR")}`,
  counterNear: "Vous approchez de la limite.",
  counterOver: "Limite dépassée : raccourcissez le texte.",
  preview: {
    title: "Aperçu",
    linkedin: "Aperçu LinkedIn",
    youtube: "Aperçu YouTube",
    now: "Maintenant",
    seeMore: "…voir plus",
    seeLess: "voir moins",
    emptyBody: "Le texte du post apparaîtra ici.",
    emptyTitle: "Titre de la vidéo",
    reactions: ["J'aime", "Commenter", "Republier", "Envoyer"],
    media: "Média",
    shortBadge: "Short",
    views: "0 vue · à l'instant",
    personalProfile: "Profil LinkedIn",
  },
  approvedConfirm: {
    title: "Modifier un post validé ?",
    body: "Ce post est validé. Le modifier demandera une nouvelle validation.",
    confirm: "Modifier quand même",
  },
  locked: "Ce post est publié ou en cours de publication : il ne peut plus être modifié.",
  rejected: (reason: string) => `Refusé : ${reason}`,
  saveAndClose: "Enregistrer et fermer",
  menu: {
    cancel: "Annuler ce post",
    cancelled: "Post annulé.",
    delete: "Supprimer",
    deleted: "Post supprimé.",
  },
  more: "Plus d'actions",
} as const;
