export const navCopy = {
  today: "Aujourd'hui",
  campaigns: "Campagnes",
  calendar: "Calendrier",
  settings: "Réglages de la marque",
  collapse: "Replier la barre latérale",
  expand: "Déplier la barre latérale",
  openMenu: "Ouvrir le menu",
  help: "Aide et raccourcis",
  profile: "Profil",
  signOut: "Se déconnecter",
  superAdmin: "Super admin · ChoYou",
  brandSwitcher: {
    label: "Changer de marque",
    search: "Rechercher une marque…",
    empty: "Aucune marque trouvée.",
    create: "Nouvelle marque",
  },
  palette: {
    trigger: "Rechercher ou aller à…",
    sidebarLabel: "Rechercher",
    placeholder: "Rechercher une campagne, un post, une action…",
    empty: "Aucun résultat. Essayez un autre mot.",
    loading: "Recherche…",
    groups: {
      actions: "Actions",
      navigation: "Aller à",
      campaigns: "Campagnes",
      posts: "Posts",
      brands: "Changer de marque",
      theme: "Thème",
    },
    createCampaign: "Créer une campagne",
    importExcel: "Importer un Excel",
    downloadTemplate: "Télécharger le modèle Excel",
    themeLight: "Thème clair",
    themeDark: "Thème sombre",
    themeSystem: "Thème du système",
  },
  shortcuts: {
    title: "Raccourcis clavier",
    description: "Gagnez du temps avec ces raccourcis, disponibles partout dans Campaign.",
    items: [
      { keys: ["Ctrl", "K"], label: "Ouvrir la palette de commandes" },
      { keys: ["Échap"], label: "Fermer un panneau ou une fenêtre" },
      { keys: ["Ctrl", "Entrée"], label: "Action principale d'un panneau" },
      { keys: ["J"], label: "Post suivant (dans l'éditeur)" },
      { keys: ["K"], label: "Post précédent (dans l'éditeur)" },
    ],
    contact: "Une question ? Écrivez à l'équipe ChoYou.",
  },
  noBrand: {
    title: "Aucune marque pour le moment",
    body: "Votre compte est prêt, mais vous n'avez encore accès à aucune marque. Demandez à un administrateur de vous inviter.",
    bodyAdmin: "Créez la première marque pour commencer à planifier des campagnes.",
    create: "Créer une marque",
  },
} as const;
