export const planningCopy = {
  mode: { label: "Affichage du planning", calendar: "Calendrier", list: "Liste" },
  views: { month: "Mois", week: "Semaine", list: "Liste" },
  viewLabel: "Vue du calendrier",
  today: "Aujourd'hui",
  previous: "Période précédente",
  next: "Période suivante",
  moved: (day: string) => `Déplacé au ${day}`,
  movedSoon: "Attention : ce post part dans moins d'une heure.",
  noText: "Pas encore de texte",
  locked: "Publié ou en cours de publication : ce post ne peut plus être déplacé.",
  emptyTitle: "Aucun post planifié",
  emptyBody: "Cliquez sur un jour du calendrier ou sur « Ajouter un post » pour commencer.",
  emptyBrandBody: "Les posts des campagnes de la marque apparaîtront ici.",
  quickCreate: {
    title: "Nouveau post",
    description: (day: string) => `Planifié le ${day}. Vous compléterez le texte ensuite.`,
    descriptionNoDay: "Choisissez le jour et le compte. Vous compléterez le texte ensuite.",
    campaign: "Campagne",
    publisher: "Publié par",
    publisherHint: "Un compte de la marque, ou un relais depuis son profil LinkedIn.",
    accounts: "Comptes de la marque",
    contributors: "Relais",
    noPublisher: "Ajoutez d'abord un compte ou un relais dans les réglages de la marque.",
    format: "Format",
    content: "Contenu",
    contentNone: "Aucun",
    date: "Jour",
    time: "Heure",
    submit: "Créer et rédiger",
    created: "Post créé.",
  },
  table: {
    select: "Sélectionner",
    selectAll: "Tout sélectionner",
    date: "Date",
    channel: "Canal",
    format: "Format",
    content: "Contenu",
    status: "Statut",
    text: "Texte",
    sortBy: (column: string) => `Trier par ${column}`,
    selected: (n: number) => (n === 1 ? "1 post sélectionné" : `${n} posts sélectionnés`),
    clear: "Désélectionner",
  },
  bulk: {
    shift: "Décaler…",
    shiftTitle: "Décaler les posts sélectionnés",
    shiftDays: "Nombre de jours",
    shiftHint: "Nombre négatif pour avancer. L'heure de chaque post est conservée.",
    shiftSubmit: "Décaler",
    shifted: (n: number, days: number) =>
      `${n} post${n > 1 ? "s" : ""} décalé${n > 1 ? "s" : ""} de ${days} jour${Math.abs(days) > 1 ? "s" : ""}.`,
    time: "Changer l'heure…",
    timeTitle: "Changer l'heure des posts sélectionnés",
    timeLabel: "Nouvelle heure",
    timeSubmit: "Appliquer",
    timed: (n: number, time: string) =>
      `${n} post${n > 1 ? "s" : ""} programmé${n > 1 ? "s" : ""} à ${time}.`,
    delete: "Supprimer",
    deleted: (n: number) => `${n} post${n > 1 ? "s" : ""} supprimé${n > 1 ? "s" : ""}.`,
  },
  brandCalendar: {
    title: "Calendrier",
    description: "Tous les posts des campagnes en cours de la marque.",
  },
} as const;
