export const settingsCopy = {
  title: "Réglages de la marque",
  description: "Identité, comptes, accès et relais de la marque.",
  tabs: {
    brand: "Général",
    prompt: "Prompt IA",
    accounts: "Comptes",
    access: "Accès",
    contributors: "Relais",
  },
  brand: {
    title: "Identité de la marque",
    description:
      "Ces réglages s'appliquent à toute l'interface, aux e-mails et aux kits des relais.",
    name: "Nom de la marque",
    color: "Couleur principale",
    colorHint:
      "Sert d'accent dans l'interface. Elle est ajustée automatiquement si elle manque de contraste.",
    colorAdjusted: (theme: string) => `Ajustée en thème ${theme} pour rester lisible.`,
    logo: "Adresse du logo",
    logoHint: "Lien direct vers une image (PNG ou SVG), par exemple hébergée sur votre site.",
    timezone: "Fuseau horaire",
    timezoneHint: "Les dates et heures des publications sont saisies et affichées dans ce fuseau.",
    address: "Adresse de la marque dans Campaign",
    preview: "Aperçu",
    previewButton: "Action principale",
  },
  prompt: {
    title: "Prompt de la marque",
    description:
      "Ces consignes guident l'IA pour chaque texte de la marque. Quelques phrases par rubrique suffisent ; tout est enregistré automatiquement.",
    editorialLine: "Ligne éditoriale",
    editorialLineHint: "De quoi parle la marque, pour qui, avec quel angle.",
    editorialLinePlaceholder:
      "Ex. : décrypter la transformation numérique des entreprises pour les décideurs IT, avec des témoignages concrets.",
    tone: "Ton",
    toneHint: "Comment la marque s'exprime.",
    tonePlaceholder: "Ex. : expert mais accessible, concret, chaleureux. Vouvoiement.",
    dos: "À faire",
    dosHint: "Les habitudes qui marchent.",
    dosPlaceholder: "Ex. : commencer par une accroche forte, citer des chiffres.",
    donts: "À éviter",
    dontsHint: "Ce que l'IA ne doit jamais faire (emojis compris).",
    dontsPlaceholder: "Ex. : pas de superlatifs creux, pas plus de deux emojis.",
    examples: "Exemples de posts",
    examplesHint:
      "Des publications réelles que vous aimez : l'IA s'en inspire pour le style, sans les recopier.",
    exampleBody: (n: number) => `Exemple ${n}`,
    exampleNote: "Pourquoi il est réussi (facultatif)",
    exampleNotePlaceholder: "Ex. : très commenté, bonne accroche",
    addExample: "Ajouter un exemple",
    removeExample: (n: number) => `Retirer l'exemple ${n}`,
    examplesMax: "5 exemples au maximum.",
    hashtags: "Hashtags de la marque",
    hashtagsHint: "Tapez un hashtag puis Entrée. L'IA en choisit 3 à 5 par post.",
    hashtagsPlaceholder: "Ajouter un hashtag…",
    removeHashtag: (tag: string) => `Retirer #${tag}`,
    defaultCta: "Appel à l'action par défaut",
    defaultCtaHint: "Utilisé quand la campagne n'en précise pas.",
    defaultCtaPlaceholder: "Ex. : Regardez la vidéo complète.",
    mentionHandle: "Compte à mentionner",
    mentionHandleHint: "La page que les relais doivent taguer.",
    mentionHandlePlaceholder: "IT for Business",
    extra: "Instructions supplémentaires",
    extraHint: "Tout ce qui ne rentre pas ailleurs.",
    extraPlaceholder: "Ex. : toujours écrire « IT for Business » en entier.",
    sandbox: {
      title: "Tester le prompt",
      description:
        "Générez un post d'essai avec les consignes telles qu'elles sont à l'écran, même non enregistrées.",
      format: "Format",
      angle: "Sujet du post d'essai",
      anglePlaceholder: "Ex. : annoncer la sortie de la vidéo LDDLT",
      run: "Générer un post d'essai",
      rerun: "Générer à nouveau",
      stop: "Arrêter",
      running: "Rédaction en cours…",
      note: "Chaque essai compte dans la limite quotidienne d'IA de la marque.",
    },
  },
  accounts: {
    title: "Comptes de publication",
    description:
      "Pages LinkedIn et chaînes YouTube de la marque. Les publications des collaborateurs depuis leur profil passent par les relais.",
    add: "Ajouter un compte",
    edit: "Modifier le compte",
    empty: "Aucun compte pour le moment",
    emptyBody:
      "Ajoutez la page LinkedIn et la chaîne YouTube de la marque pour planifier des posts.",
    platform: "Réseau",
    name: "Nom du compte",
    namePlaceholder: "IT for Business",
    url: "Adresse de la page ou de la chaîne",
    kitContributor: "Qui publie sur cette page ?",
    kitContributorHint:
      "Cette personne recevra un kit (texte, média, démarche) pour publier chaque post validé.",
    kitNone: "À définir plus tard",
    kitTo: (name: string) => `Kit envoyé à ${name}`,
    modeLinkedIn: "Publication avec un kit envoyé à la personne qui gère la page.",
    modeYouTube:
      "Programmation à la main dans YouTube Studio ; Campaign fournit titre et description.",
    posts: (n: number) => (n === 0 ? "Aucun post" : n === 1 ? "1 post" : `${n} posts`),
    inactive: "Désactivé",
    deactivate: "Désactiver",
    reactivate: "Réactiver",
    deactivated: (name: string) => `« ${name} » est désactivé.`,
    saved: "Compte enregistré.",
    create: "Ajouter le compte",
    open: (name: string) => `Ouvrir ${name} dans un nouvel onglet`,
  },
  access: {
    title: "Accès",
    description: "Les personnes qui peuvent voir ou modifier les campagnes de la marque.",
    invite: "Inviter une personne",
    inviteTitle: "Inviter une personne",
    inviteDescription:
      "Elle recevra un e-mail pour rejoindre la marque. L'invitation est valable 7 jours.",
    email: "Adresse e-mail",
    role: "Rôle",
    clientCanApprove: "Peut valider les posts",
    clientCanApproveRemove: "Retirer le droit de validation",
    clientCanApproveHint: "Le client pourra valider ou refuser les posts de sa marque.",
    send: "Envoyer l'invitation",
    sent: (email: string) => `Invitation envoyée à ${email}.`,
    notSent: "E-mails désactivés en développement : copiez le lien d'invitation ci-dessous.",
    copyLink: "Copier le lien",
    members: "Membres",
    pending: "Invitations en attente",
    pendingEmpty: "Aucune invitation en attente.",
    you: "vous",
    superAdminNote:
      "Les super admins de l'équipe ChoYou ont accès à toutes les marques, sans apparaître ici.",
    expires: (date: string) => `Expire le ${date}`,
    resend: "Renvoyer",
    revoke: "Annuler l'invitation",
    revoked: "Invitation annulée.",
    remove: "Retirer l'accès",
    removeTitle: (name: string) => `Retirer l'accès de ${name} ?`,
    removeBody: "Cette personne ne verra plus la marque. Vous pourrez l'inviter à nouveau.",
    removed: "Accès retiré.",
    roleChanged: "Rôle mis à jour.",
    roleHints: {
      ADMIN: "Tout, y compris les comptes, les relais et les accès.",
      VALIDATOR: "Rédiger, valider les posts et lancer les campagnes.",
      EDITOR: "Rédiger et soumettre les posts en validation.",
      CLIENT: "Voir sa marque et commenter ; valider si autorisé.",
    },
  },
  contributors: {
    title: "Relais",
    description:
      "Les collaborateurs qui publient ou relaient depuis leur propre profil LinkedIn. Ils n'ont pas besoin de compte Campaign.",
    add: "Ajouter un relais",
    edit: "Modifier le relais",
    empty: "Aucun relais pour le moment",
    emptyBody: "Ajoutez les collaborateurs qui publieront ou relaieront les posts de la marque.",
    firstName: "Prénom",
    lastName: "Nom",
    email: "Adresse e-mail",
    emailHint: "Les kits de publication seront envoyés à cette adresse.",
    jobTitle: "Poste",
    linkedinUrl: "Profil LinkedIn",
    search: "Rechercher un relais…",
    noResult: "Aucun relais ne correspond à votre recherche.",
    posts: (n: number) =>
      n === 0 ? "Aucune publication" : n === 1 ? "1 publication" : `${n} publications`,
    inactive: "Désactivé",
    deactivate: "Désactiver",
    reactivate: "Réactiver",
    deactivated: (name: string) => `${name} est désactivé.`,
    saved: "Relais enregistré.",
    create: "Ajouter le relais",
  },
  newBrand: {
    title: "Nouvelle marque",
    description:
      "Créez l'espace d'une marque ou d'un client. Vous pourrez compléter les réglages ensuite.",
    name: "Nom de la marque",
    namePlaceholder: "Nom du client ou de la marque",
    color: "Couleur principale",
    submit: "Créer la marque",
    created: (name: string) => `La marque « ${name} » est prête.`,
  },
} as const;
