export const wizardCopy = {
  pageTitle: "Nouvelle campagne",
  breadcrumb: "Nouvelle campagne",
  resumeBreadcrumb: "Assistant",
  steps: [
    { title: "L'essentiel", short: "Essentiel" },
    { title: "Le brief", short: "Brief" },
    { title: "Le planning", short: "Planning" },
    { title: "Récapitulatif", short: "Récap" },
  ],
  stepOf: (n: number) => `Étape ${n} sur 4`,
  stepsLabel: "Étapes de l'assistant",
  back: "Retour",
  next: "Continuer",
  saveAndQuit: "Enregistrer et quitter",
  draftSaved: "Brouillon enregistré. Vous pourrez reprendre à cette étape.",
  autosaveHint: "Tout est enregistré automatiquement en brouillon.",
  errors: {
    name: "Donnez un nom à la campagne.",
    date: "Choisissez une date valide.",
    endBeforeStart: "La date de fin doit être après la date de début.",
  },
  step1: {
    intro: "Commençons par l'essentiel. Seul le nom est obligatoire, le reste peut attendre.",
    brand: "Marque",
    name: "Nom de la campagne",
    nameHint: "Un nom court que toute l'équipe reconnaîtra, par exemple « Promotion vidéo LDDLT ».",
    startDate: "Date de début",
    startDateHint: "Le lundi de la première semaine de publication.",
    notMonday: "Ce n'est pas un lundi. Les semaines du planning commenceront ce jour-là.",
    endDate: "Date de fin",
    endDateHint: "Facultative.",
    objective: "Objectif",
    objectiveHint: "En une phrase : ce que la campagne doit obtenir.",
    objectivePlaceholder:
      "Faire connaître la vidéo LDDLT auprès des DSI et générer 50 inscriptions.",
  },
  step2: {
    intro: "Le brief guide la rédaction des posts. Quelques phrases suffisent.",
    audience: "Cible",
    audienceHint: "À qui s'adressent les publications ?",
    audiencePlaceholder: "Ex. : DSI et responsables IT d'entreprises de 200 à 2 000 salariés.",
    keyMessage: "Message clé",
    keyMessageHint: "L'idée que le lecteur doit retenir.",
    keyMessagePlaceholder:
      "La transformation numérique réussit quand les équipes métier sont impliquées.",
    callToAction: "Appel à l'action",
    callToActionHint: "Ce que le lecteur doit faire ensuite.",
    callToActionPlaceholder: "Ex. : regarder la vidéo complète sur YouTube.",
    brief: "Brief détaillé",
    briefHint: "Contexte, ton, points à mettre en avant ou à éviter.",
    mainContent: "Contenu principal",
    mainContentHint: "La vidéo ou le document autour duquel tourne la campagne.",
    mainContentNone: "Aucun pour l'instant",
    addMainContent: "Ajouter la vidéo principale",
    addAnotherContent: "Ajouter une autre vidéo",
    mainContentTitle: "Titre de la vidéo",
    mainContentLink: "Lien du média (Frame.io, Drive…)",
    mainContentAdd: "Ajouter",
    mainContentAdded: "Vidéo principale ajoutée.",
    helper: {
      open: "M'aider à écrire le brief",
      title: "Écrire le brief avec l'IA",
      description:
        "Trois questions rapides, puis l'IA propose la cible, le message clé, l'appel à l'action et le brief. Vous pourrez tout modifier.",
      loading: "Préparation des questions…",
      answerPlaceholder: "Votre réponse (facultatif)",
      write: "Rédiger le brief",
      writing: "Rédaction du brief…",
      applied: "Brief rédigé : relisez-le et ajustez-le si besoin.",
      cancel: "Annuler",
    },
    exampleToggle: "Voir un exemple de bon brief",
    example:
      "La vidéo LDDLT (12 min) montre comment trois DSI ont mené leur transformation. Nous voulons qu'elle soit vue par des décideurs IT, pas seulement par notre réseau. Ton : expert mais accessible, concret, sans jargon marketing. Mettre en avant les témoignages et les chiffres (–30 % de tickets). Éviter les superlatifs et les promesses vagues. Chaque capsule met en avant une idée de la vidéo et renvoie vers la version longue.",
  },
  step3: {
    intro: "Comment voulez-vous construire le planning ?",
    choicesLabel: "Façon de construire le planning",
    importTitle: "Importer un fichier Excel",
    importBody:
      "Reprenez un planning existant ou le modèle Campaign : aperçu et corrections avant la création des posts.",
    importAction: "Importer un fichier",
    templateAction: "Télécharger le modèle",
    aiTitle: "Laisser l'IA proposer un planning",
    aiBody:
      "À partir du brief, des dates et des contenus de la campagne. Vous gardez ce qui vous convient.",
    blankTitle: "Partir d'un calendrier vide",
    blankBody:
      "Ajoutez les posts directement dans le calendrier de la campagne : un clic sur un jour suffit.",
    selected: "Choisi",
    planner: {
      propose: "Proposer un planning",
      proposing: "Préparation du planning…",
      again: "Nouvelle proposition",
      intro: (n: number) =>
        `${n} publication${n > 1 ? "s" : ""} proposée${n > 1 ? "s" : ""}. Décochez ce qui ne vous convient pas, ajustez les sujets, puis créez les posts.`,
      caption: "Planning proposé par l'IA",
      columns: {
        keep: "Garder",
        when: "Quand",
        account: "Compte",
        format: "Format",
        content: "Contenu",
        angle: "Sujet / angle",
      },
      keep: (label: string) => `Garder : ${label}`,
      angleLabel: (label: string) => `Sujet de ${label}`,
      when: (week: number, day: string, time: string) => `S${week} · ${day} ${time}`,
      create: (n: number) => (n === 1 ? "Créer 1 post" : `Créer ${n} posts`),
      creating: "Création des posts…",
      created: (n: number) =>
        n === 1
          ? "1 post créé dans le calendrier de la campagne."
          : `${n} posts créés dans le calendrier de la campagne.`,
      none: "Cochez au moins une publication.",
    },
  },
  step4: {
    intro: "Voici où en est votre campagne. Vous pouvez l'ouvrir pour planifier les posts.",
    posts: "Posts planifiés",
    byChannel: (linkedin: number, youtube: number) =>
      `LinkedIn : ${linkedin} · YouTube : ${youtube}`,
    contents: "Contenus",
    contentsWithoutMedia: (n: number) =>
      n === 0 ? "Tous ont un lien média" : `${n} sans lien média`,
    postsWithoutText: "Posts sans texte",
    postsWithoutTextHint: "Ils pourront être rédigés plus tard.",
    brief: "Brief",
    briefFilled: "Renseigné",
    briefEmpty: "À compléter",
    noPostsYet: "Aucun post pour l'instant : vous les ajouterez dans le calendrier.",
    saveDraft: "Enregistrer en brouillon",
    open: "Ouvrir la campagne",
  },
} as const;
