export const wizardCopy = {
  pageTitle: "Nouvelle campagne",
  breadcrumb: "Nouvelle campagne",
  resumeBreadcrumb: "Assistant",
  steps: [
    { title: "L'essentiel", short: "Essentiel" },
    { title: "Le brief", short: "Brief" },
    { title: "Le planning", short: "Planning" },
    { title: "Récapitulatif", short: "Récap" },
  ],
  stepOf: (n: number) => `Étape ${n} sur 4`,
  stepsLabel: "Étapes de l'assistant",
  back: "Retour",
  next: "Continuer",
  saveAndQuit: "Enregistrer et quitter",
  draftSaved: "Brouillon enregistré. Vous pourrez reprendre à cette étape.",
  autosaveHint: "Tout est enregistré automatiquement en brouillon.",
  errors: {
    name: "Donnez un nom à la campagne.",
    date: "Choisissez une date valide.",
    endBeforeStart: "La date de fin doit être après la date de début.",
  },
  step1: {
    intro: "Commençons par l'essentiel. Seul le nom est obligatoire, le reste peut attendre.",
    brand: "Marque",
    name: "Nom de la campagne",
    nameHint: "Un nom court que toute l'équipe reconnaîtra, par exemple « Promotion vidéo LDDLT ».",
    startDate: "Date de début",
    startDateHint: "Le lundi de la première semaine de publication.",
    notMonday: "Ce n'est pas un lundi. Les semaines du planning commenceront ce jour-là.",
    endDate: "Date de fin",
    endDateHint: "Facultative.",
    objective: "Objectif",
    objectiveHint: "En une phrase : ce que la campagne doit obtenir.",
    objectivePlaceholder:
      "Faire connaître la vidéo LDDLT auprès des DSI et générer 50 inscriptions.",
  },
  step2: {
    intro: "Le brief guide la rédaction des posts. Quelques phrases suffisent.",
    audience: "Cible",
    audienceHint: "À qui s'adressent les publications ?",
    audiencePlaceholder: "Ex. : DSI et responsables IT d'entreprises de 200 à 2 000 salariés.",
    keyMessage: "Message clé",
    keyMessageHint: "L'idée que le lecteur doit retenir.",
    keyMessagePlaceholder:
      "La transformation numérique réussit quand les équipes métier sont impliquées.",
    callToAction: "Appel à l'action",
    callToActionHint: "Ce que le lecteur doit faire ensuite.",
    callToActionPlaceholder: "Ex. : regarder la vidéo complète sur YouTube.",
    brief: "Brief détaillé",
    briefHint: "Contexte, ton, points à mettre en avant ou à éviter.",
    mainContent: "Contenu principal",
    mainContentHint: "La vidéo ou le document autour duquel tourne la campagne.",
    mainContentNone: "Aucun pour l'instant",
    addMainContent: "Ajouter la vidéo principale",
    addAnotherContent: "Ajouter une autre vidéo",
    mainContentTitle: "Titre de la vidéo",
    mainContentLink: "Lien du média (Frame.io, Drive…)",
    mainContentAdd: "Ajouter",
    mainContentAdded: "Vidéo principale ajoutée.",
    exampleToggle: "Voir un exemple de bon brief",
    example:
      "La vidéo LDDLT (12 min) montre comment trois DSI ont mené leur transformation. Nous voulons qu'elle soit vue par des décideurs IT, pas seulement par notre réseau. Ton : expert mais accessible, concret, sans jargon marketing. Mettre en avant les témoignages et les chiffres (–30 % de tickets). Éviter les superlatifs et les promesses vagues. Chaque capsule met en avant une idée de la vidéo et renvoie vers la version longue.",
  },
  step3: {
    intro: "Comment voulez-vous construire le planning ?",
    blankTitle: "Partir d'un calendrier vide",
    blankBody:
      "Ajoutez les posts directement dans le calendrier de la campagne : un clic sur un jour suffit.",
    selected: "Choisi",
  },
  step4: {
    intro: "Voici où en est votre campagne. Vous pouvez l'ouvrir pour planifier les posts.",
    posts: "Posts planifiés",
    byChannel: (linkedin: number, youtube: number) =>
      `LinkedIn : ${linkedin} · YouTube : ${youtube}`,
    contents: "Contenus",
    contentsWithoutMedia: (n: number) =>
      n === 0 ? "Tous ont un lien média" : `${n} sans lien média`,
    postsWithoutText: "Posts sans texte",
    postsWithoutTextHint: "Ils pourront être rédigés plus tard.",
    brief: "Brief",
    briefFilled: "Renseigné",
    briefEmpty: "À compléter",
    noPostsYet: "Aucun post pour l'instant : vous les ajouterez dans le calendrier.",
    saveDraft: "Enregistrer en brouillon",
    open: "Ouvrir la campagne",
  },
} as const;
